<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Activity Dashboard</title>
    <link rel="stylesheet" href="style.css">
    <!-- Import Chart.js for creating charts -->
    <script src="https://cdn.jsdelivr.net/npm/chart.js"></script>
</head>
<body>

    <header>
        <h1>Activity Dashboard</h1>
    </header>

    <main class="dashboard-grid">

        <!-- Key Stats Cards -->
        <div class="card stat-card">
            <h2>Total Commits</h2>
            <p id="total-count">0</p>
        </div>
        <div class="card stat-card">
            <h2>Earliest Date</h2>
            <p id="earliest-date">-</p>
        </div>
        <div class="card stat-card">
            <h2>Latest Date</h2>
            <p id="latest-date">-</p>
        </div>

        <!-- Heatmap for Weekdays -->
        <div class="card">
            <h2>Activity by Day of Week</h2>
            <div id="heatmap-container" class="heatmap">
                <!-- Heatmap will be generated by JavaScript -->
            </div>
        </div>

        <!-- Column Chart by Year -->
        <div class="card chart-card">
            <h2>Activity by Year</h2>
            <canvas id="year-chart"></canvas>
        </div>

        <!-- Column Chart by Month and Year -->
        <div class="card chart-card">
            <h2>Activity by Month</h2>
            <canvas id="month-year-chart"></canvas>
        </div>

    </main>

    <script src="script.js"></script>
</body>
</html>
